Repository nginx-proxy/acme-companion, pull requests merged in 2020-12, with the labels that each got.

#723 Update acme.sh to 2.8.8
  Dockerfile
Labels: Dependencies

#724 Allow ZEROSSL_API_KEY on the letsencrypt container
  app/letsencrypt_service
Labels: Documentation Update, Enhancement

#726 Improve the Zero SSL documentation
  docs/Zero-SSL.md
Labels: Documentation Update

#727 Fix LETSENCRYPT_KEYSIZE feature and tests
  app/cleanup_test_artifacts
  app/letsencrypt_service
  docs/Let's-Encrypt-and-ACME.md
  test/config.sh
  test/tests/acme_accounts/expected-std-out.txt
  test/tests/certs_san/expected-std-out.txt
  test/tests/certs_single/expected-std-out.txt
  test/tests/certs_single_domain/expected-std-out.txt
  test/tests/certs_standalone/expected-std-out.txt
  test/tests/default_cert/expected-std-out.txt
  test/tests/force_renew/expected-std-out.txt
  test/tests/permissions_custom/expected-std-out.txt
  test/tests/permissions_default/expected-std-out.txt
  test/tests/private_keys/expected-std-out.txt
  test/tests/private_keys/run.sh
  test/tests/unit_tests/expected-std-out.txt
Labels: Bug, CI/Tests, Documentation Update

#738 Migrate CI to GitHub Actions as Travis CI is ending their free OSS builds
  .github/workflows/test.yml
  .travis.yml
  test/github_actions/containers-logs.sh
  test/run.sh
  test/setup/docker-gen/Dockerfile
  test/setup/nginx-proxy/Dockerfile
  test/setup/setup-boulder.sh
  test/setup/setup-local.sh
  test/setup/setup-nginx-proxy.sh
  test/tests/acme_accounts/run.sh
  test/tests/certs_san/run.sh
  test/tests/certs_single/run.sh
  test/tests/certs_single_domain/run.sh
  test/tests/certs_standalone/run.sh
  test/tests/container_restart/run.sh
  test/tests/default_cert/run.sh
  test/tests/docker_api/run.sh
  test/tests/force_renew/run.sh
  test/tests/location_config/run.sh
  test/tests/permissions_custom/run.sh
  test/tests/permissions_default/run.sh
  test/tests/private_keys/run.sh
  test/tests/symlinks/run.sh
  test/travis/containers-logs.sh
  test/travis/update-docker-compose.sh
Labels: CI/Tests

#740 Add OCSP Must-Staple extension feature
  .github/workflows/test.yml
  app/letsencrypt_service
  app/letsencrypt_service_data.tmpl
  docs/Let's-Encrypt-and-ACME.md
  test/config.sh
  test/tests/ocsp_must_staple/expected-std-out.txt
  test/tests/ocsp_must_staple/run.sh
Labels: Enhancement

#741 Use patch level releases in Dockerfile's FROM
  Dockerfile
Labels: Dependencies

#743 Use Pebble for tests.
  .github/workflows/test.yml
  app/letsencrypt_service
  docs/Container-configuration.md
  test/config.sh
  test/github_actions/containers-logs.sh
  test/setup/pebble-config.json
  test/setup/setup-boulder.sh
  test/setup/setup-local.sh
  test/setup/setup-nginx-proxy.sh
  test/setup/setup-pebble.sh
  test/tests/acme_accounts/run.sh
  test/tests/certs_san/run.sh
  test/tests/certs_single/run.sh
  test/tests/certs_single_domain/run.sh
  test/tests/certs_standalone/run.sh
  test/tests/container_restart/run.sh
  test/tests/force_renew/run.sh
  test/tests/ocsp_must_staple/run.sh
  test/tests/permissions_custom/run.sh
  test/tests/permissions_default/run.sh
  test/tests/private_keys/run.sh
  test/tests/symlinks/run.sh
  test/tests/test-functions.sh
Labels: CI/Tests
