Repository nginx-proxy/acme-companion, pull requests merged in 2020-03, with the labels that each got.

#626 fix typo
  docs/Basic-usage.md
Labels: Documentation Update

#632 Remove deprecated keys / aliases from .travis.yml
  .travis.yml
Labels: CI/Tests

#628 Upgrade golang build stage and alpine image
  Dockerfile
Labels: Chore

#637 Update simp_le to 0.18.0
  install_simp_le.sh
Labels: Bug, lgtm, simp_le issue

#640 Multi-domains certificates examples
  README.md
  docs/Let's-Encrypt-and-ACME.md
Labels: Documentation Update

#641 Shellcheck linting
  app/cert_status
  app/entrypoint.sh
  app/force_renew
  app/functions.sh
  app/letsencrypt_service
  app/start.sh
Labels: Chore
