Repository nginx-proxy/acme-companion, pull requests merged in 2024-05, with the labels that each got.

#1106 ci: bump artifact actions from 3 to 4
  .github/workflows/test.yml
Labels: type/ci

#1078 fix: handle most recently created containers first
  app/letsencrypt_service_data.tmpl
Labels: type/fix

#1092 fix: get container ID from /proc/self/mountinfo (for podman)
  app/functions.sh
Labels: type/fix

#1120 test: upgrade pebble to 2.5.2
  .github/workflows/test.yml
  test/config.sh
  test/setup/pebble/.env
  test/setup/pebble/docker-compose.yml
  test/setup/pebble/pebble-config-eab.json
  test/setup/pebble/pebble-config.json
Labels: type/ci, type/test
